### ISSUE TITLE
Container image for LTP

### ISSUE THREAD

**Issue by Anjali05** [linux-test-project/ltp#660] opened 2020-03-24 20:33 UTC
Is there any container image for LTP that I can run with docker?

**Comment by metan-ucw** [comment] 2020-03-24 20:49
No, and it does not even make sense to make one.

**Comment by pevik** [comment] 2020-03-24 20:54
We don't provide any, but our travis setup uses Docker. We generate various `Dockerfile` files in [.travis.yml](https://github.com/linux-test-project/ltp/blob/master/.travis.yml) with help of scripts in [travis](https://github.com/linux-test-project/ltp/tree/master/travis) directory.

But are you aware that due Docker architecture you'll be testing kernel of the host system which runs Docker? We use travis just for compilation tests, not for running tests.

**Comment by Anjali05** [comment] 2020-03-25 14:57
@pevik I want to run it with different runtime of docker such as runc (the default one) and runsc(https://github.com/google/gvisor). The idea is to run LTP as a workload on these platforms and  study the coverage we get on the host using lcov. I did try installing  LTP inside a ubuntu container and running it but tests did not run. I am not sure if LTP depends on some flags/features in the kernel which might be missing in the standard ubuntu image.

**Comment by metan-ucw** [comment] 2020-03-25 15:05
@Anjali05 that's strange, installing and running LTP should be as simple as ./configure && make && make install. Then you can run tests in the /opt/ltp/ directory with the runltp script. That should just work fine.

**Comment by Anjali05** [comment] 2020-03-25 15:07
@metan-ucw I will give it a try again

**Comment by pevik** [comment] 2020-03-25 15:34
Or you can use openSUSE, there are already built packages:
https://build.opensuse.org/package/show/benchmark/ltp (latest release)
https://build.opensuse.org/package/show/benchmark:ltp:devel/ltp (nightly builds)

But if you compile with Ubuntu, just look at the travis configuration I sent:
Dependencies for Debian/Ubuntu: https://github.com/linux-test-project/ltp/blob/master/travis/debian.sh
Then you can build it either just with `./build.sh` or traditionally with `make autotools && ./configure && make && make install` (for git sources) or `./configure && make && make install` (for downloaded released tarball).

**Comment by Anjali05** [comment] 2020-03-30 01:40
@pevik I installed it using the commands you suggested. I want to run all the test cases, however, when I try changing directory to /opt/ltp as mentioned in the installation guide I get "No such file or directory". I did not give any install directory path when I ran the command. This is the output of ls:


<img width="1362" alt="ls" src="https://user-images.githubusercontent.com/8316863/77867548-541be400-71fd-11ea-8ce4-19e31b654bbb.png">

I see `runltp` but when I try to run it I get this error:

![image](https://user-images.githubusercontent.com/8316863/77867574-6f86ef00-71fd-11ea-9358-3265d8d24a70.png)

I am not sure if I am missing something here.

Thanks

**Comment by metan-ucw** [comment] 2020-03-30 08:59
@Anjali05 and have you looked at the log? The error is shown there quite clear, you are missing /dev/kmsg.

**Comment by Anjali05** [comment] 2020-03-30 19:58
@metan-ucw I needed to run the container in --privileged mode as by default it does not have access to  /dev/kmsg. Thanks

**Comment by Anjali05** [comment] 2020-03-31 16:00
@metan-ucw @pevik Is there any way I can disable kmsg logging in ltp?

**Comment by Anjali05** [comment] 2020-04-01 02:20
@metan-ucw @pevik I am getting error while `make` on alpine linux. I did ran this script(https://github.com/linux-test-project/ltp/blob/master/travis/alpine.sh) to make sure all prerequisites are met: 

![image](https://user-images.githubusercontent.com/8316863/78092417-587b0500-7395-11ea-8867-885229053f04.png)

Am I missing something here?

**Comment by pevik** [comment] 2020-04-01 10:32
Well, the script removes not yet supported files, including `utils/benchmark/ebizzy-0.3` directory. So you didn't run it, because it fails on it. Just run that script before compilation. And this error is clearly written in red in the log :).

**Comment by metan-ucw** [comment] 2020-04-01 11:23
@Anjali05 There is an option for disabling the kmsg logging, just look at ./runltp -h output.

**Comment by Anjali05** [comment] 2020-04-01 13:14
> Well, the script removes not yet supported files, including `utils/benchmark/ebizzy-0.3` directory. So you didn't run it, because it fails on it. Just run that script before compilation. And this error is clearly written in red in the log :).

Can I skip these unsupported tests in then?

**Comment by Anjali05** [comment] 2020-04-01 13:16
I was trying to run the tests in the ubuntu container but it seems it is getting stuck at fork09 test:

![image](https://user-images.githubusercontent.com/8316863/78141299-edf7b280-73f0-11ea-9b78-3dd7c067f561.png)

I have two questions:
* Is there any way I can skip the tests which are getting stuck?
* Where is the log file generated so that I can check what the issue is when the test is stuck?

**Comment by metan-ucw** [comment] 2020-04-01 13:28
No idea why it got stuck, the fork09 shouldn't do anything problematic. Also debugging kernel testcases is tricky for a few different reasons, if something in kernel gets corrupted it can manifest much later while a different test is running, Linux kernel is asynchronous in order to be fast.

Usually the kernel console is being written to a log on a different machine over serial line to catch kernel stack traces. If things get stuck you can do a kernel crash dump that can be analyzed later on, etc. For containers it's especially tricky because you can easily crash or corrupt the host kernel.

You can pass skiplist to runltp script if you want but that would mean a lot of trial and error.

**Comment by Anjali05** [comment] 2020-04-03 20:56
@pevik @metan-ucw I ran the script before compilation on alpine but it seems like some other testcases are failing:

![image](https://user-images.githubusercontent.com/8316863/78404206-8180dd00-75c3-11ea-8a80-31495846d8ee.png)

I am not sure if there is some problem in my setup or do these test cases also fail usually?  Should I remove these also before compilation?

**Comment by Anjali05** [comment] 2020-04-03 21:47
@pevik @metan-ucw These failed on my setup:

testcases/kernel/syscalls/accept4/*.c
testcases/kernel/syscalls/ioctl/*.c
testcases/kernel/pty/*.c

**Comment by pevik** [comment] 2020-04-04 16:36
If you delete files via https://github.com/linux-test-project/ltp/blob/master/travis/alpine.sh, you need to run master. If you compile latest release, you need to delete more files (https://github.com/linux-test-project/ltp/blob/20200120/travis/alpine.sh).
Or, better, just use `travis/alpine.sh` from the sources you're compiling. But this is really obvious :(.

**Comment by Anjali05** [comment] 2020-04-06 19:23
@pevik @metan-ucw Is there any way to add a timeout on tests like if some test is stuck for too long, skip it and proceed?

**Comment by pevik** [comment] 2020-04-07 07:08
Not sure if I understand you. Do you worry that some tests fails? That's natural (kernel is a software, so it has bugs). `runltp` supports skipping certain tests (see `/opt/ltp/runltp -h`). Also there is timeout (default 5 min), which can be adjusted if you have slow machine (https://github.com/linux-test-project/ltp/wiki/User-Guidelines LTP_TIMEOUT_MUL).

**Comment by Anjali05** [comment] 2020-04-07 13:25
@pevik I am not worried it the tests fail, some are bound to fail. But in my case, some test cases are getting stuck and hence, the program is not proceeding. I know there is a timeout I can apply to the whole program. I want to know if there is a way I can apply a timeout for tests. To elaborate, if test X is taking too long to execute, can the program skip it and proceed with the next test. I do not want to exit the program when a particular test takes a while but would want to proceed with the next test.

**Comment by pevik** [comment] 2020-04-07 17:55
No. You can increase the timeout or skip tests which are problematic.

**Comment by metan-ucw** [comment] 2020-04-08 13:03
@Anjali05 There are timeouts implemented in LTP, if test gets stuck it's likely because of kernel bug. Which test have you seen stuck?

**Comment by Anjali05** [comment] 2020-04-08 13:55
These: fork09, keyctl01, msgstress04. I have added them to SKIPFILE for now.

**Comment by metan-ucw** [comment] 2020-04-09 09:22
Hmm so these are two stress tests and then keyctl01 and the keyctl01 shouldn't really do anything that may get it stuck, so either that one exposed problem caused by a different test or there is a bug in your kernel.

**Comment by metan-ucw** [comment] 2020-04-24 11:21
Can we close the issue no?

**Closed** 2020-04-27 00:56 UTC
