### ISSUE TITLE
open_posix_testsuite:  Why the test failed？

### ISSUE THREAD

**Issue by haidong-yao** [linux-test-project/ltp#893] opened 2021-12-16 02:56 UTC
PC:  ubuntu20.04

run: ./run-all-posix-option-group-tests.sh

error log:

aio_error/3-1.c return code didn't match expected value (0 != 22).
aio_return/2-1.c Second call to aio_return() may return -1; aio_return() returned 111
aio_return/3-2.c aio_return() may fail with (-1, 22); failed with (4096, 0) instead
aio_return/4-1.caio_return() have not failed
.....
UNTESTED: shm_open() did not fail with ENAMETOLONG
UNTESTED: shm_open() did not fail with ENAMETOLONG
UNTESTED: shm_open() did not fail with ENAMETOLONG
UNTESTED: shm_open() did not fail with ENAMETOLONG

[run-all-posix-option-group-tests.log](https://github.com/linux-test-project/ltp/files/7724227/run-all-posix-option-group-tests.log)

**Comment by metan-ucw** [comment] 2021-12-16 10:03
The pthread_rwlock_rdlock() failures are caused by long standing bug in glibc see https://sourceware.org/bugzilla/show_bug.cgi?id=25619. For the rest of the failures you will have to look at the tests and figure out why yourself.

Also note that UNTESTED (and possibly some of the UNRESOLVED) are not failures, there is quite a lot of optional behavior in POSIX in the case of UNTESTED for shm_open() there simply is no artificial limit hence the call does not fail with ENAMETOLONG.

**Comment by haidong-yao** [comment] 2021-12-16 11:45
Thanks

**Comment by metan-ucw** [comment] 2022-02-03 11:45
Let's close this now.

**Closed by metan-ucw** 2022-02-03 11:45 UTC
