### ISSUE TITLE
can_run_tests.sh literal vs string

### ISSUE THREAD

**Issue by steven-unruh** [linux-test-project/ltp#564] opened 2019-09-06 18:33 UTC
/opt/ltp/testcases/bin/can_run_tests.sh: line 65: ip link add dev vcan0 type vcan failed: ret - 2: command not found

that line of code is:
        if [ $ret -ne 0 ]; then
                tst_brkm TBROK
----->                         "ip link add dev $VCAN type vcan failed: ret - $ret"
        fi

looks to be using this line as a literal instead as a string for the test

**Comment by steven-unruh** [comment] 2019-09-06 18:38
i see the same in all of these:
/opt/ltp/testcases/bin/can_run_tests.sh: line 30: tst_require_root: command not found
/opt/ltp/testcases/bin/can_run_tests.sh: line 65: ip link add dev vcan0 type vcan failed: ret - 2: command not found
/opt/ltp/testcases/bin/dns-stress: line 45: tst_require_root: command not found
/opt/ltp/testcases/bin/dns-stress: line 46: tst_test_cmds: command not found
/opt/ltp/testcases/bin/dns-stress: line 60: tst_tmpdir: command not found
/opt/ltp/testcases/bin/mc_cmds.sh: line 42: ROD: command not found
/opt/ltp/testcases/bin/mc_cmds.sh: line 45: tst_tmpdir: command not found
/opt/ltp/testcases/bin/mc_commo.sh: line 39: tst_test_cmds: command not found
/opt/ltp/testcases/bin/mc_commo.sh: line 44: tst_tmpdir: command not found
/opt/ltp/testcases/bin/mc_member.sh: line 41: tst_test_cmds: command not found
/opt/ltp/testcases/bin/mc_member.sh: line 42: tst_tmpdir: command not found
/opt/ltp/testcases/bin/rlogin01.sh: line 28: tst_test_cmds: command not found
/opt/ltp/testcases/bin/sendfile01.sh: line 50: tst_test_cmds: command not found
/opt/ltp/testcases/bin/sendfile01.sh: line 52: tst_tmpdir: command not found
/opt/ltp/testcases/bin/ssh-stress: line 48: tst_require_root: command not found
/opt/ltp/testcases/bin/ssh-stress: line 49: tst_test_cmds: command not found
/opt/ltp/testcases/bin/ssh-stress: line 60: tst_tmpdir: command not found
/opt/ltp/testcases/bin/tcpdump01.sh: line 32: tst_test_cmds: command not found
/opt/ltp/testcases/bin/tcpdump01.sh: line 35: tst_tmpdir: command not found
/opt/ltp/testcases/bin/telnet01.sh: line 28: tst_test_cmds: command not found
/opt/ltp/testcases/bin/tst_net.sh: line 102: tst_require_root: command not found
/opt/ltp/testcases/bin/tst_net.sh: line 107: tst_test_cmds: command not found
/opt/ltp/testcases/bin/tst_net.sh: line 333: tst_test_cmds: command not found
/opt/ltp/testcases/bin/tst_net.sh: line 480: tst_test_cmds: command not found
/opt/ltp/testcases/bin/xinetd_tests.sh: line 115: ROD: command not found
/opt/ltp/testcases/bin/xinetd_tests.sh: line 128: ROD: command not found
/opt/ltp/testcases/bin/xinetd_tests.sh: line 31: tst_tmpdir: command not found
/opt/ltp/testcases/bin/xinetd_tests.sh: line 33: tst_test_cmds: command not found
/opt/ltp/testcases/bin/xinetd_tests.sh: line 75: ROD: command not found

**Comment by steven-unruh** [comment] 2019-09-06 18:48
fyi this is against 

4.18.0-135.el8.ppc64le #1 SMP Fri Aug 16 19:25:25 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux

**Comment by pevik** [comment] 2019-09-09 08:02
> /opt/ltp/testcases/bin/can_run_tests.sh: line 65: ip link add dev vcan0 type vcan failed: ret - 2: command not found
> 
> that line of code is:
> if [ $ret -ne 0 ]; then
> tst_brkm TBROK
> -----> "ip link add dev $VCAN type vcan failed: ret - $ret"
> fi
> 
> looks to be using this line as a literal instead as a string for the test

Thanks for a bug report. Feel free to send a patch to mailing list or a pull request.
I can fix it myself (please give me your email, I'll add `Reported-by: your name <your email>` tag in commit message).

**Comment by pevik** [comment] 2019-09-09 08:05
> i see the same in all of these:
> /opt/ltp/testcases/bin/can_run_tests.sh: line 30: tst_require_root: command not found
> /opt/ltp/testcases/bin/can_run_tests.sh: line 65: ip link add dev vcan0 type vcan failed: ret - 2: command not found
...

All of these command not find are caused by `tst_test.sh` not in `$PATH`. You need to have `${LTPROOT}/testcases/bin:${LTPROOT}/bin` in your `$PATH` (where `LTPROOT` is where LTP is installed, by default `/opt/ltp` directory). The best is to run LTP with `runltp` script, which adjust `PATH` (among other things). For more info see [1]

[1] https://github.com/linux-test-project/ltp#quick-guide-to-running-the-tests

**Comment by chetjain** [comment] 2019-09-10 05:13
> 
> 
> > i see the same in all of these:
> > /opt/ltp/testcases/bin/can_run_tests.sh: line 30: tst_require_root: command not found
> > /opt/ltp/testcases/bin/can_run_tests.sh: line 65: ip link add dev vcan0 type vcan failed: ret - 2: command not found
> > ...
> 
> All of these command not find are caused by `tst_test.sh` not in `$PATH`. You need to have `${LTPROOT}/testcases/bin:${LTPROOT}/bin` in your `$PATH` (where `LTPROOT` is where LTP is installed, by default `/opt/ltp` directory). The best is to run LTP with `runltp` script, which adjust `PATH` (among other things). For more info see [1]
> 
> [1] https://github.com/linux-test-project/ltp#quick-guide-to-running-the-tests

Yes, it is just a matter of PATH.  I verified on 4.18.0-135.el8.ppc64le and the tests PASSED.
@steven-unruh please ping me separately, if you would like to understand, how to use the exports.

**Comment by steven-unruh** [comment] 2019-09-10 15:17
that may have fixed most but not all

i used
export LTPROOT=/opt/ltp
export LHOST=sunruh
export IPV4_LHOST=10.33.16.31
export LHOST_IFACES=enP49155p1s0
export RHOST=vimlp7
export IPV4_RHOST=10.33.0.185
export RHOST_IFACES=env2
export TST_USE_SSH=1

and still got these 2
[root@sunruh tmp]# grep "command" fail.sep09 | grep -v rsh
/opt/ltp/testcases/bin/can_run_tests.sh: line 65: ip link add dev vcan0
type vcan failed: ret - 2: command not found
/opt/ltp/testcases/bin/can_run_tests.sh: line 65: ip link add dev vcan0
type vcan failed: ret - 2: command not found

there are others but not related

**Comment by chetjain** [comment] 2019-09-10 16:09
Spoke to Steve and clarified about the failure on his system.
(1) test.sh was referring to some other local testcases path, so all tst_* related functions were failing
(2) The following modules were missing again.
iproute2               iproute2-ss180813
iputils                iputils-s20180629
LTP does not install required modules automatically. It is user responsibility to load/install those modules prior to test run.

**Comment by pevik** [comment] 2019-09-11 08:14
I'm closing a ticket as it's a configuration issue. Feel free to reopen with additional info if you think there is a bug.

**Closed by pevik** 2019-09-11 08:14 UTC

**Comment by pevik** [comment] 2019-09-11 08:15
> Spoke to Steve and clarified about the failure on his system.
> (1) test.sh was referring to some other local testcases path, so all tst_* related functions were failing
> (2) The following modules were missing again.
> iproute2 iproute2-ss180813
> iputils iputils-s20180629
> LTP does not install required modules automatically. It is user responsibility to load/install those modules prior to test run.

As I wrote, legacy API does not support defining test dependencies. This should be solved once tests are migrated to use new shell API.

**Comment by steven-unruh** [comment] 2019-09-11 12:28
thanks for the help
