### ISSUE TITLE
sendfile01 test error is fulled of screen, and can not be end

### ISSUE THREAD

**Issue by luckymoon** [linux-test-project/ltp#524] opened 2019-04-24 10:10 UTC
when i use ./runltp -N to run all test,  then code are jammed
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''
sendfile01 2 TBROK: 'pkill testsf_s6' failed on '': ''

**Comment by pevik** [comment] 2019-05-21 12:07
Can you please test `sendfile01` itself? Assuming you installed LTP into default location `/opt/ltp`, run it like:

`PATH="/opt/ltp/testcases/bin:$PATH" LTPROOT=/opt/ltp /opt/ltp/testcases/bin/sendfile01 -6`

Works nicely in my case:
```
sendfile01 1 TINFO: initialize 'lhost' 'ltp_ns_veth2' interface
sendfile01 1 TINFO: set local addr 10.0.0.2/24
sendfile01 1 TINFO: set local addr fd00:1:1:1::2/64
sendfile01 1 TINFO: initialize 'rhost' 'ltp_ns_veth1' interface
sendfile01 1 TINFO: set remote addr 10.0.0.1/24
sendfile01 1 TINFO: set remote addr fd00:1:1:1::1/64
sendfile01 1 TINFO: Network config (local -- remote):
sendfile01 1 TINFO: ltp_ns_veth2 -- ltp_ns_veth1
sendfile01 1 TINFO: 10.0.0.2/24 -- 10.0.0.1/24
sendfile01 1 TINFO: fd00:1:1:1::2/64 -- fd00:1:1:1::1/64
sendfile01 1 TINFO: Doing /opt/ltp/testcases/bin/sendfile01.
sendfile01 1 TINFO: testsf_c6 ip 'fd00:1:1:1::1' port '53722' file 'ascii.sm'
sendfile01 1 TINFO: testsf_c6 ip 'fd00:1:1:1::1' port '53722' file 'ascii.med'
sendfile01 1 TINFO: testsf_c6 ip 'fd00:1:1:1::1' port '53722' file 'ascii.lg'
sendfile01 1 TINFO: testsf_c6 ip 'fd00:1:1:1::1' port '53722' file 'ascii.jmb'
sendfile01 1 TPASS: test finished successfully
```

`runltp` is deprecated (needs to be replaced with something reasonable), preferred way to run network stress is to use `network.sh` script, e.g.:

`/opt/ltp/testscripts/network.sh -6`

**Comment by CentUser** [comment] 2019-09-10 07:14
LOL, runltp is deprecated? I wander what is the main feature that LTP delivers...
Or, I think we should update the doc...

**Comment by pevik** [comment] 2019-09-10 08:27
`network.sh` is the best what is currently available for network tests.
It's documented on https://github.com/linux-test-project/ltp/tree/master/testcases/network

For non-networking tests there is not yet anything better than `runltp`. There is ongoing work, not finished yet (see https://people.kernel.org/metan/towards-parallel-kernel-test-runs for rewrite).

I'm not able to reproduce it, thus closing a ticket. Feel free to reopen it with additional info, if the problem persists for you.

**Closed by pevik** 2019-09-10 08:27 UTC
Labels: need info, network
