### ISSUE TITLE
perf_event_open02 fails quite often

### ISSUE THREAD

**Issue by Wjjoye** [linux-test-project/ltp#1060] opened 2023-08-21 02:40 UTC
Hello Community,
I have a question
Setup: LTP v20220121, GLP
cmdline="perf_event_open02"
contacts=""
analysis=exit
<<<test_output>>>
incrementing stop
tst_test.c:1431: TINFO: Timeout per run is 0h 05m 00s
perf_event_open02.c:104: TINFO: bench_work estimated loops = 3949 in 500 ms
perf_event_open02.c:149: TINFO: [0] value:1580354307 time_enabled:494797844 time_running:494797844
perf_event_open02.c:149: TINFO: [1] value:1580362947 time_enabled:494831997 time_running:494831997
perf_event_open02.c:149: TINFO: [2] value:1580359942 time_enabled:494879114 time_running:494879114
perf_event_open02.c:149: TINFO: [3] value:1580369163 time_enabled:494985998 time_running:494985998
perf_event_open02.c:149: TINFO: [4] value:1580358205 time_enabled:494876267 time_running:494876267
perf_event_open02.c:149: TINFO: [5] value:1580367364 time_enabled:494902345 time_running:494902345
perf_event_open02.c:149: TINFO: [6] value:1350994814 time_enabled:496075152 time_running:424030496
perf_event_open02.c:308: TINFO: nhw: 6, overall task clock: 3973373101
perf_event_open02.c:309: TINFO: hw sum: 75860770852, task clock sum: 23840742750
perf_event_open02.c:321: TINFO: ratio: 6.000127
perf_event_open02.c:323: TFAIL: test failed (ratio was greater than 6)
Probabilistic failure, please help guide me

**Comment by metan-ucw** [comment] 2023-08-21 14:21
What this is is a rounding failure, the ration should be <= 6 as there are 6 CPU hardware counters. First check that the number of hardware counters in your CPU matches. Secondly we had seen such failures before the test was changed to run under realtime FIFO priority and the threads were pinned to a single CPU, since frequent context switches and task migration introduced rounding errors in the samplings. However that should have been fixed in 2019 so if there is a rounding error it's caused by something else.

**Comment by Wjjoye** [comment] 2023-08-22 00:26
How to troubleshoot this problem. It is probabilistic, sometimes successful, sometimes failed

**Comment by Wjjoye** [comment] 2023-09-08 07:14
thanks

**Closed** 2023-09-08 07:14 UTC
