### ISSUE TITLE
Is it possible to run LTP remotely 

### ISSUE THREAD

**Issue by Vertigo0709** [linux-test-project/ltp#127] opened 2017-01-13 10:42 UTC
I may be asking for an unnecessary thing, but due to our current testing environment, I would like to run LTP remotely (from a local workstation machine, connect to an remote machine (where LTP is installed) and run all testcases).

I see that now "runltp" supported to run all testcases. It's very impressive. But connect to remote machine and run "runltp" may meet some issue due to our read-only system, some sporadic resets (then the connection will be losted).

I'm still concerned if "runltp" should be updated, or I'll write another one (touching to long "runltp" is quite painful for me now).
Actually we had an already-run script long time ago, but it depends on a (local) list of testcases, and we have to maintain it manually. I see that our current "runltp" script running base on default group (/opt/ltp/scenario_groups/default), and I really prefer to apply it for our script (so that no need to handle local list of testcase. 

Is it valuable if we (remake and) push a script with feature like this? Just 1 or 2 scripts in local machine, LTP should be in remote machine. Main function is just simply run all testcase remotely, I'll let the spaces of some additional scripts for users (like pre-config/install LTP in remote machine - they can decide to install or mount .., or reset remote machine if ping is not stable etc..).

Still some first of our ideas, so if you have any more idea or see any un-applicable points, please share me with me :-)

Thanks a lot in advance

**Comment by richiejp** [comment] 2017-01-13 12:30
I think the general consensus is to handle this sort of thing in a third party test runner. We primarily use OpenQA (https://openqa.suse.de/tests/overview?distri=sle&version=12-SP3&build=0207&groupid=70) and twopence (https://github.com/openSUSE/twopence). There are probably plenty of other solutions out there as well, I would recommend doing some research into existing solutions before rolling your own. 

Using either OpenQA or twopence you can execute runltp or parse the runtest files directly. The latter is the preferred method, but a lot less easy to begin with. For configuring machines and installing software, there are many solutions such as SaltStack (https://saltstack.com/) and OpenQA can do it, although it might be too heavy for what you want.

**Comment by olerem** [comment] 2017-01-16 05:54
The problem with "third party test runner" is a need to integrate all of it to our own "third party test runner". LTP is only one of test suits running on our system. After previous experience on integration of "third party test runner" in to other "third party test runner" i personally would like to avoid this kind of design :)
IMO, the need to runtest files directly still need more maintenance in comparison to running scenario_groups.
@metan-ucw  what is your opinion?

**Comment by metan-ucw** [comment] 2017-01-16 10:14
I'm not against having some very basic test runner script in LTP that can be configured to ssh to a remote machine, run a test there and store results locally. Clearly this lightweight solution would be sufficient for some usages and it would be a good starting point for anyone who wants to integrate LTP into a third party test runner as well.

But the script should be very basic, just executing testcases and storing the results. Any machine installation or setup is out of scope for this kind of a script.

**Comment by fkromer** [comment] 2017-11-28 16:50
A bit late but what is the current state of this issue? [twopence](https://github.com/openSUSE/twopence) or any other tool which eases ssh access/handling and which enables `scp`'ing (I use Python [pexpect](http://pexpect.readthedocs.io/en/stable/index.html) for these kind of tasks) should be sufficient. Even the setup of LTP on the remote machine itself could be triggered with such a tool without any prerequisites besides a internet connection.

**Comment by metan-ucw** [comment] 2018-02-27 14:06
Well not much happened in LTP upstream. We do have somehow working test runner in openQA https://openqa.opensuse.org/tests/619906 for instance, so I'm pretty sure that we are at least aware of the actual challenges.

The main problem is that LTP often crashes the system under test (which is a good thing because most of the time that's caused by unpatched kernel CVE etc.) and hence the automation framework has to be able to recover from that in order to get fully automatic test-runs.

The end result is that you really need two machines to run LTP, one that runs the tests and collects the results and one that actually runs the tests + infrastructure how to recover from kernel panic on the SUT. I'm pretty sure that this can be done with some amount of scripts and qemu so that we end up with a script that gets a path to an installed system image with pre-defined root password and end up with LTP test results after a hour or two, but so far nobody has taken on the challenge.

**Comment by fkromer** [comment] 2018-02-27 14:23
> Well not much happened in LTP upstream. We do have somehow working test runner in openQA https://openqa.opensuse.org/tests/619906 for instance, so I'm pretty sure that we are at least aware of the actual challenges.

I will check this out.

> The main problem is that LTP often crashes the system under test (which is a good thing because most of the time that's caused by unpatched kernel CVE etc.) and hence the automation framework has to be able to recover from that in order to get fully automatic test-runs.

Right.

> The end result is that you really need two machines to run LTP, one that runs the tests and collects the results and one that actually runs the tests + infrastructure how to recover from kernel panic on the SUT.

Couldn't run the *test and collection* and the *test and infrastructure* tasks in the same machine? (I don't understand your desired setup I guess.)

> I'm pretty sure that this can be done with some amount of scripts and qemu so that we end up with a script that gets a path to an installed system image with pre-defined root password and end up with LTP test results after a hour or two, but so far nobody has taken on the challenge.

In my case qemu is not the best solution because the (embedded) system doesn't really fit the most reasonable qemu. I would probably have to ssh onto the real system.

**Comment by fkromer** [comment] 2018-02-27 14:29
@metan-ucw 

> I'm not against having some very basic test runner script in LTP that can be configured to ssh to a remote machine, run a test there and store results locally. Clearly this lightweight solution would be sufficient for some usages and it would be a good starting point for anyone who wants to integrate LTP into a third party test runner as well.
>
> But the script should be very basic, just executing testcases and storing the results. Any machine installation or setup is out of scope for this kind of a script.

Wouldn't it be possible to "dockerize" a remote execution setup which makes use of LTP (instead of extending LTP with this functionality itself)?

**Comment by metan-ucw** [comment] 2018-02-27 14:45
@fkromer 

1. Unfortunately the openQA test runner is probably not reusable.

2. I cannot image how you can recover from a kernel crash reliably, if you the testrunner that logs test results runs on the same machine as the actual test. There is no guarantees whatsoever when the kernel crashes and rather often than not the logs are completely corrupted in that case. Hence the logic that decides which test to run and writes the logs has to be on a separate machine. The very same machine would then look for timeouts and reboots the machine that runs the tests (SUT) if it stops responding or if you catch kernel trace on serial console.

3. For embedded you need to be able to reboot the real machine (relay on a power line or something that can be triggered from the machine that collects the logs) instead of rebooting the qemu virtual machine. But the overall logic would be similar. The same can be done for severs with IPMI, instead of rebooting qemu, the machine would be rebooted by IPMI.

4. Docker will not help you when kernel crashes, with docker you have only one kernel that runs different distros in containers, the whole thing will go down if one of them triggers kernel oops or panic.

**Comment by fkromer** [comment] 2018-02-27 15:13
> 2. I cannot image how you can recover from a kernel crash reliably, if you the testrunner that logs test results runs on the same machine as the actual test. There is no guarantees whatsoever when the kernel crashes and rather often than not the logs are completely corrupted in that case. Hence the logic that decides which test to run and writes the logs has to be on a separate machine. The very same machine would then look for timeouts and reboots the machine that runs the tests (SUT) if it stops responding or if you catch kernel trace on serial console.

Right. See 4.

> 3. For embedded you need to be able to reboot the real machine (relay on a power line or something that can be triggered from the machine that collects the logs) instead of rebooting the qemu virtual machine. But the overall logic would be similar. The same can be done for severs with IPMI, instead of rebooting qemu, the machine would be rebooted by IPMI.

Right. Thanks for the hint with IPMI.

> 4. Docker will not help you when kernel crashes, with docker you have only one kernel that runs different distros in containers, the whole thing will go down if one of them triggers kernel oops or panic.

It was probably unclear in my description. I meant to "dockerize" the host side (everything needed to trigger the test execution on the remote system and collection of test results from the remote system, scripts which transfer everything needed to execute the tests on the remote system onto the remote system, etc.). In case the remote system crashes it can be restore via the power line and probably it is also possible to get test execution results until the crash occurred from some kind of dump onto the host.

**Comment by metan-ucw** [comment] 2018-02-27 15:41
@fkromer 
Any system that expects that logs are saved correctly up to a kernel crash is broken by design, you really need to initiate each single test execution from the remote machine and feed the test output back ideally via serial line. Which means especially that there are no scripts to collect results on the SUT, you just have to be able to log to that machine and run test there. All preparation that has to be done on the SUT is LTP installation, the rest should be handled by the remote machine.

The way how openQA handles that is that the openQA server downloads the list of tests from the SUT, then triggers execution of them one after another, if the SUT timeouts you know which test has triggered the crash because it was the last one you executed there. The SUT has to be as dumb as possible since you cannot trust that it will save any file correctly.

**Comment by fkromer** [comment] 2018-02-27 16:18
@metan-ucw You are right. Triggering test execution one after another is the most reliable way. In case the SUT didn't crash and the interface of choice is still alive the result of the test can either be requested by the host side or pushed on the remote side. (Right now I can only think of requesting it from the host side. As you said this keeps the SUT setup as simple as possible by just getting the LTP on there.)

**Comment by richiejp** [comment] 2018-02-28 09:40
This may not be relevant, but I think the ideal setup for an embedded system would be something like the following:

1) Communication: 1 or 2 serial ports. One port is used to capture the kernel log and the other is used control the SUT (e.g. by logging into a serial terminal and using `expect`). If there is only one serial port then it can be used for both.

2) Setup: Connect the SUT to a bootable storage device controlled (or even emulated) by the test runner. When the SUT is shutdown the storage device can be inspected by the test runner and overwritten with a good image.

This would give you a system almost as quick and flexible as running the tests in a VM. Although getting (2) to work could be quite difficult (or impossible depending on the hardware) and would make the test environment quite different from production depending on how it is implemented.

Also there is https://www.linaro.org/initiatives/lava/ which I think runs too much on the SUT compared to OpenQA, but is being actively used with embedded systems.

**Comment by olerem** [comment] 2018-02-28 10:00
Or labgrid, which IMO more suitable for this use case:
https://github.com/labgrid-project/labgrid

**Comment by fkromer** [comment] 2018-02-28 10:06
> This may not be relevant, but I think the ideal setup for an embedded system would be something like the following:
> 
> 1. Communication: 1 or 2 serial ports. One port is used to capture the kernel log and the other is used control the SUT (e.g. by logging into a serial terminal and using expect). If there is only one serial port then it can be used for both.

Right now I would be happy with *any* remote setup :wink: I like the idea of capturing the kernel log (in addition to the test execution results). What do you mean with "control the SUT" exactly?

> 2. Setup: Connect the SUT to a bootable storage device controlled (or even emulated) by the test runner. When the SUT is shutdown the storage device can be inspected by the test runner and overwritten with a good image.
> 
> This would give you a system almost as quick and flexible as running the tests in a VM. Although getting (2) to work could be quite difficult (or impossible depending on the hardware) and would make the test environment quite different from production depending on how it is implemented.

Right. But in my case this is no option. Right now I cannot think of how to technically implement it without getting too far from production.

**Comment by olerem** [comment] 2018-02-28 10:11
mount ltp executables over NFS is kind of usable workaround. If SUT/DUT is designed with security in mind,, then no tests should be possible to execute. At least not LTP :)
Any way, most development tests are done on device with software configured for development ...

**Comment by fkromer** [comment] 2018-02-28 10:11
@olerem labgrid looks interesting...

**Comment by olerem** [comment] 2018-02-28 10:13
@fkromer labgrid was designed with exactly this experience and use case in mind.

**Comment by richiejp** [comment] 2018-02-28 15:08
> Right now I would be happy with any remote setup wink I like the idea of capturing the kernel log (in addition to the test execution results). What do you mean with "control the SUT" exactly?

Usually sending commands to a TTY on the SUT. It appears Labgrid handles that somehow.

**Comment by fkromer** [comment] 2018-02-28 15:17
@richiejp Yepp. [labgrids drivers](https://labgrid.readthedocs.io/en/latest/configuration.html#drivers) seems to be quite extensive.

**Comment by olerem** [comment] 2018-02-28 16:43
this BSP includes some tests based on labgrid:
https://git.pengutronix.de/cgit/OSELAS.BSP-Pengutronix-J1939/log/?h=bst/x86-wip
read this:
https://git.pengutronix.de/cgit/OSELAS.BSP-Pengutronix-J1939/tree/README-J1939?h=bst/x86-wip

yaml config with drivers:
https://git.pengutronix.de/cgit/OSELAS.BSP-Pengutronix-J1939/tree/configs/platform-qemu/integration.yaml?h=bst/x86-wip

some project specific tests:
https://git.pengutronix.de/cgit/OSELAS.BSP-Pengutronix-J1939/tree/configs/platform-qemu/test-j1939?h=bst/x86-wip

**Comment by metan-ucw** [comment] 2021-02-17 13:07
Let's close this one as there was no discussion for a last few years.

**Closed by metan-ucw** 2021-02-17 13:07 UTC
