### ISSUE TITLE
run "./runltp -f ltp-aiodio.part3" failed

### ISSUE THREAD

**Issue by jie2xzhou** [linux-test-project/ltp#971] opened 2022-09-14 06:30 UTC
The test error is caused by "No such file or directory".
The test command is "./runltp -f ltp-aiodio.part3"
The call sequence is following:
runltp -> ltp-pan -> ltp-aiodio.part3
And I find in no place create "$TMPDIR/aiodio.$$" directory.

output:
<<<test_start>>>
tag=FSX034 stime=1662538554
cmdline="fsx-linux -l 500000 -r 4096 -N 10000 $TMPDIR/aiodio.$$/junkfile"
contacts=""
analysis=exit
<<<test_output>>>
/tmp/ltp-qFoktcygy7/aiodio.435919/junkfile: No such file or directory
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=91 corefile=no
cutime=0 cstime=1
<<<test_end>>>

After I change junkfile to exist directory, the test is OK.
diff ltp-aiodio.part3_org ltp-aiodio.part3
4,5c4,5
< FSX032 fsx-linux -l 500000 -r 4096 -t 4096 -w 4096 -N 10000 $TMPDIR/aiodio.$$/junkfile
< FSX033 fsx-linux -l 500000 -r 4096 -t 2048 -w 2048 -N 10000 $TMPDIR/aiodio.$$/junkfile
---
> FSX032 fsx-linux -l 500000 -r 4096 -t 4096 -w 4096 -N 10000 $TMPDIR/junkfile.$$
> FSX033 fsx-linux -l 500000 -r 4096 -t 2048 -w 2048 -N 10000 $TMPDIR/junkfile.$$

test output:
tag=FSX032 stime=1662538553
cmdline="fsx-linux -l 500000 -r 4096 -t 4096 -w 4096 -N 10000 $TMPDIR/junkfile.$$"
contacts=""
analysis=exit
<<<test_output>>>
skipping zero size read
truncating to largest ever: 0x2c000
truncating to largest ever: 0x55000
truncating to largest ever: 0x5e000
truncating to largest ever: 0x74000
truncating to largest ever: 0x75000
truncating to largest ever: 0x79000
skipping zero size read
skipping zero size read
skipping zero size read
skipping zero size read
skipping zero size read
truncating to largest ever: 0x7a000
skipping zero size read
skipping zero size read
skipping zero size read
skipping zero size read
All operations completed A-OK!
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=0 corefile=no
cutime=17 cstime=10
<<<test_end>>>

**Comment by metan-ucw** [comment] 2022-09-14 08:38
This is a duplicate of #261

**Closed by metan-ucw** 2022-09-14 08:38 UTC
