### ISSUE TITLE
ext4-subdir-limit case fail

### ISSUE THREAD

**Issue by LiliDeng** [linux-test-project/ltp#526] opened 2019-04-28 06:09 UTC
Test failed for below reason:
ext4-subdir-limit 1 TBROK: /dev/sdc should be umounted before test
Can we add check and do umount before starting real testing?

**Comment by pevik** [comment] 2019-04-29 09:56
Is it a bug in a test not properly unmounting `$LTP_BIG_DEV`and thus failing when repeating testing `ext4_subdir_limit_test.sh`? Can you please describe how to reproduce it?

I think writer intention when requiring device under `$LTP_BIG_DEV` unmounted was data loss prevention. Although SUT should not contain any important data and `/` or any other used device cannot be unmounted anyway, I'd still prefer not doing it and leave it for user (unless it's a bug in a test not properly unmounting, which should be fixed).

**Comment by pevik** [comment] 2019-04-29 10:13
FYI #527 is related to this issue.

**Comment by xuyang0410** [comment] 2019-11-15 01:34
Since ltp has deleted ext4 features tests after commit  [29f51a85b122](https://github.com/linux-test-project/ltp/commit/29f51a85b122c08744d759286b9b54de95ec89aa) ,  only two cases (ext4-nsec-timestamps,ext4-subdir-limit) is transfering into [xfstests](https://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git/). It is in reviewing [fstests: transport two ext4 tests from LTP](https://www.spinics.net/lists/fstests/msg13042.html). I think we can close this issue.

**Closed** 2019-11-15 08:47 UTC
Labels: bug
