### ISSUE TITLE
After run network.sh in Rhel8.1, it shows “No such file or directory”, which makes the result FAIL

### ISSUE THREAD

**Issue by Gene-Lo** [linux-test-project/ltp#666] opened 2020-04-22 06:32 UTC
【Test Result】
After run network.sh in Rhel8.1, it shows “No such file or directory”, which makes the result FAIL
After we copy some files to their correct path by manual, the errors of "No such file or directory" never happen. However, there are still some other errors happen, which still make the test-result FAIL.

【Expect Result】
After run network.sh, it should show PASS.

【Test Steps】
Install LTP, edit network.sh, and then run it via cmd "./network.sh -6mnrstcdaebiTUDSRMF".
For more details about how we install network.sh and adjust files’ path, please refer to below documents:
《20200414_SOP of network.sh Test & SOL-log》
[20200414_SOP.of.network.sh.Test.SOL-log.zip](https://github.com/linux-test-project/ltp/files/4514198/20200414_SOP.of.network.sh.Test.SOL-log.zip)

【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.8.1.el8_1.ppc64le

[FW configuration]
BMC: op940.15.mih-1-0-g7983355f4
PNOR: OP9-v2.4-4.40-prod

[HW configuration]
CPU DD2.3 20core *2
Micron (MTA18ASF2G72PZ-2G9E1) 16G *32
Seagate Jaguar 400GB *1
PSU ACBEL 2000w *2

**Comment by pevik** [comment] 2020-04-22 07:15
This is an invalid report.

Looking at TXT, `TCONF` means something prevents to run the test, many of them are that you need to install test dependencies.
```
bind_noport01 7 TCONF: server failed
busy_poll01 1 TCONF: busy poll not supported
busy_poll02 1 TCONF: busy poll not supported
busy_poll03 1 TCONF: busy poll not supported
dccp01 2 TCONF: server failed
dccp_ipsec 1 TCONF: server failed
dccp_ipsec_vti 1 TCONF: server failed
dctcp01 1 TCONF: netem doesn't support ECN
dhcpd_tests 1 TCONF: 'dhcpd' not found
dns-stress 1 TCONF: 'named' not found
fsx 1 TCONF: UDP support disabled on NFS server
iptables01 1 TCONF: 'telnet' not found
mpls03 1 TCONF: mpls + ip6gre requires kernel 4.19+
nfs01 1 TCONF: UDP support disabled on NFS server
nfs02 1 TCONF: UDP support disabled on NFS server
nfs03 1 TCONF: UDP support disabled on NFS server
nfs04 1 TCONF: UDP support disabled on NFS server
nfs05 1 TCONF: UDP support disabled on NFS server
nfs06 1 TCONF: UDP support disabled on NFS server
nfslock01 1 TCONF: UDP support disabled on NFS server
nfsstat01 1 TCONF: UDP support disabled on NFS server
nft01 1 TCONF: 'telnet' not found
rlogin01 1 TCONF: 'rlogin' not found
sctp01 1 TCONF: server failed
sctp_ipsec 1 TCONF: server failed
sctp_ipsec_vti 1 TCONF: server failed
telnet01 1 TCONF: 'telnet' not found
traceroute01 1 TCONF: 'traceroute' not found
xinetd_tests 1 TCONF: 'telnet' not found
```
ftp, mcast, rcp, rsh and some of route tests haven't been rewritten into new shell network API, so they report TFAIL instead of TCONF:
```
ftp01.sh    1  TFAIL  :  ltpapicmd.c:188: Test broken: ftp: command not found
mcast4-pktfld01    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
mcast4-pktfld02    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
mcast4-queryfld01    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
mcast4-queryfld02    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
mcast4-queryfld03    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
mcast4-queryfld04    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
mcast4-queryfld05    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
mcast4-queryfld06    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
mcast6-pktfld01    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
mcast6-pktfld02    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
mcast6-queryfld01    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
mcast6-queryfld02    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
mcast6-queryfld03    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
mcast6-queryfld04    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
mcast6-queryfld05    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
mcast6-queryfld06    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
route4-redirect01    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
route4-rmmod    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
route6-redirect01    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
route6-rmmod    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
rsh01.sh    1  TFAIL  :  ltpapicmd.c:188: Test broken: rsh: command not found
rcp01.sh    1  TFAIL  :  ltpapicmd.c:188: Test broken: rcp: command not found
```

The same is with many TBROK:
sctp not supported (test should report TCONF, but first they need to be rewritten into new C API and cleaned, these are very old tests taken from other testsuite)
```
test_1_to_1_accept_close.c    1  TBROK  :  /root/ltp/utils/sctp/func_tests/../testlib/sctputil.h:137: socket: Protocol not supported
test_1_to_1_accept_close.c    2  TBROK  :  /root/ltp/utils/sctp/func_tests/../testlib/sctputil.h:137: Remaining cases broken
```

NFS tests (there are some improvements in master branch, which will be in next LTP version), again: configuration issue, you're testing v3, which is not supported by your OS. But all these `'mount.nfs: Connection refused'` are probably caused by `nfsd` daemon not being run.

```
nfs01 1 TBROK: 'mount -t nfs -o proto=tcp,vers=3 10.0.0.2:/tmp/netpan-36133/LTP_nfs01.MI2jEGkQO4/3/tcp /tmp/netpan-36133/LTP_nfs01.MI2jEGkQO4/3/0' failed on '': 'mount.nfs: requested NFS version or transport protocol is not supported'
nfs01 1 TBROK: 'mount -t nfs -o proto=tcp,vers=4 10.0.0.2:/tmp/netpan-36133/LTP_nfs01.k7AYzAA4TR/4/tcp /tmp/netpan-36133/LTP_nfs01.k7AYzAA4TR/4/0' failed on '': 'mount.nfs: Connection refused'
```
You found some *real* failures, but the threshold failures are failures of performance tests. The other you should investigate and report to RHEL (LTP cannot influence distros). But most of them are probably already reported.

```
mpls04 3 TFAIL: expected 'pass' but ret: '6'
tracepath01 1 TFAIL: failed to trace path to 'fd00:1:1:1::1'
sit01 1 TFAIL: Test failed, threshold: 80 %
gre01 1 TFAIL: Test failed, threshold: 80 %
```
BTW zipped logs which contains docx which contains images => not many people will even bother to open them.

**Closed by pevik** 2020-04-22 07:15 UTC
