### ISSUE TITLE
TFAIL  :  msgstress03.c:155: 	Fork failed

### ISSUE THREAD

**Issue by pankajjoshi347** [linux-test-project/ltp#805] opened 2021-03-30 11:55 UTC
Hi,
i am running ltp 5.10.19 and 5.10.22 custom linux kernel on riscv with LTP version: 20200515 but i am facing following issues 

Fork failed (may be OK if under stress)
Fork failed (may be OK if under stress)
Fork failed (may be OK if under stress)
Fork failed (may be OK if under stress)
Fork failed (may be OK if under stress)
Fork failed (may be OK if under stress)
msgstress03    1  TFAIL  :  msgstress03.c:155: 	Fork failed (may be OK if under stress)

Attaching the complete log file of msgstress03 along with strace output.

can someone help to get it fixed
[msgstress03_log.txt](https://github.com/linux-test-project/ltp/files/6228795/msgstress03_log.txt)
[msgs03_strace.txt](https://github.com/linux-test-project/ltp/files/6228799/msgs03_strace.txt)

**Comment by metan-ucw** [comment] 2021-05-14 12:46
Closing as duplicate of #509

**Closed by metan-ucw** 2021-05-14 12:46 UTC
