### ISSUE TITLE
clock_gettime04 fails on x86_64 randomly

### ISSUE THREAD

**Issue by idorax** [linux-test-project/ltp#799] opened 2021-03-11 08:12 UTC
Test case `clock_gettime04` fails on x86_64 randomly, the failure looks like:
```
     1	<<<test_start>>>
     2	tag=clock_gettime04 stime=1614705663
     3	cmdline="clock_gettime04"
     4	contacts=""
     5	analysis=exit
     6	<<<test_output>>>
     7	tst_test.c:1286: TINFO: Timeout per run is 0h 05m 00s
     8	vdso_helpers.c:76: TINFO: Couldn't find vdso_gettime64()
     9	clock_gettime04.c:157: TPASS: CLOCK_REALTIME: Difference between successive readings is reasonable
    10	clock_gettime04.c:150: TFAIL: CLOCK_REALTIME_COARSE: Difference between successive readings greater than 5 ms (1): 8
    11	clock_gettime04.c:157: TPASS: CLOCK_MONOTONIC: Difference between successive readings is reasonable
    12	clock_gettime04.c:150: TFAIL: CLOCK_MONOTONIC_COARSE: Difference between successive readings greater than 5 ms (0): 5
    13	clock_gettime04.c:157: TPASS: CLOCK_MONOTONIC_RAW: Difference between successive readings is reasonable
    14	clock_gettime04.c:157: TPASS: CLOCK_BOOTTIME: Difference between successive readings is reasonable
    15	
    16	Summary:
    17	passed   4
    18	failed   2
    19	broken   0
    20	skipped  0
    21	warnings 0
    22	<<<execution_status>>>
    23	initiation_status="ok"
    24	duration=0 termination_type=exited termination_id=1 corefile=no
    25	cutime=7 cstime=5
    26	<<<test_end>>>
```
* **kernel version**: `5.11.0`

@wangli5665 is helping to reproduce this failure, thanks @wangli5665 !

**Comment by wangli5665** [comment] 2021-03-15 06:53
Also failed with s390x platform, this needs more investigaion.

Kernel Version: 5.12.0-0.rc2~
Machine Architecture: s390x

     7	tst_test.c:1261: TINFO: Timeout per run is 0h 05m 00s
     8	clock_gettime04.c:84: TINFO: Running in a virtual machine, multiply the delta by 10.
     9	vdso_helpers.c:76: TINFO: Couldn't find vdso_gettime64()
    10	clock_gettime04.c:157: TPASS: CLOCK_REALTIME: Difference between successive readings is reasonable
    11	clock_gettime04.c:157: TPASS: CLOCK_REALTIME_COARSE: Difference between successive readings is reasonable
    12	clock_gettime04.c:157: TPASS: CLOCK_MONOTONIC: Difference between successive readings is reasonable
    13	clock_gettime04.c:157: TPASS: CLOCK_MONOTONIC_COARSE: Difference between successive readings is reasonable
    14	clock_gettime04.c:142: TFAIL: CLOCK_MONOTONIC_RAW: Time travelled backwards (1): -4482871389571244 ns
    15	clock_gettime04.c:157: TPASS: CLOCK_BOOTTIME: Difference between successive readings is reasonable

**Comment by wangli5665** [comment] 2021-04-08 13:10
The failure on s390x has been confirmed as a BUG and fixed in kernel commit:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5b43bd184530af6b868d8273b0a743a138d37ee8

**Comment by pevik** [comment] 2021-04-09 09:03
@wangli5665 could you please commit `linux-git` `struct tst_tag` for this test?

**Comment by wangli5665** [comment] 2021-04-09 10:35
Thanks @pevik, sounds good, I will do it later.

**Comment by xuyang0410** [comment] 2021-08-02 02:38
sorry, s390 bug has been fixed instead of x86_64, but I can't reproduce it on my machine with 5.11 kernel.

**Comment by metan-ucw** [comment] 2021-09-14 14:41
Feel free to reopen if needed.

**Closed by metan-ucw** 2021-09-14 14:41 UTC
