### ISSUE TITLE
invaliddates.c failed probabilistically 

### ISSUE THREAD

**Issue by sugarfillet** [linux-test-project/ltp#331] opened 2018-06-05 07:21 UTC
I run the invaliddates testcase in rhel7.3, it failed probabilistically. I reviewed the code and figured out that **ACCEPTABLENSECDELTA  is so small** that my testcase failed.
What I want to know is that  why invaliddates.c define ACCEPTABLENSECDELTA **5000**, is there some document declaring it，can i redefine it ?

**Comment by metan-ucw** [comment] 2018-06-05 11:28
Indeed the delta is quite small, I suppose that the engineer who wrote the test just did a guess and hardcoded the value there. We should at least multiply it by 10.

For me the test also fails with EINVAL for timespec {0, 0} and all small enough values, looking at kernel git this is intentional and caused by:
https://github.com/torvalds/linux/commit/e1d7ba8735551ed79c7a0463a042353574b96da3

**Comment by sugarfillet** [comment] 2018-06-08 01:58
Thanks for your reply, @metan-ucw 

> We should **at least** multiply it by 10.

Can I arbitrarily enlarge the delta according to my local OS environment JUST for passing my testcase？ Or there is some limit for the delta？

>For me the test also fails with EINVAL for timespec {0, 0} and all small enough values, looking at kernel >git this is intentional and caused by:
torvalds/linux@e1d7ba8

My kernel doesn't refer to the [e1d7ba8](https://github.com/torvalds/linux/commit/e1d7ba8735551ed79c7a0463a042353574b96da3). I haven't seen EINVAL yet by now.

**Comment by metan-ucw** [comment] 2018-06-12 10:32
> Can I arbitrarily enlarge the delta according to my local OS environment JUST for passing my testcase？ Or there is some limit for the delta？

The problem here is quite complex, the test sets time and then gets it back, generally there is no guaranteed upper bound for time elapsed between two syscalls on multitasking system. So we have to stick with some reasonable approximation. Usually this will be fast as timers are most commonly implemented using vDSO, but may be slower on systems where vDSO is not available. On preemtive kernel scheduler can even stop the process in the second clock_gettime() syscall before we happen to fill the time into the user specified buffer and we may as well have to wait until the process gets to run again, which may cause larger delta.

In practice the original test ACCEPTABLENSECDELTA is too small and will probably work only on very fast vDSO systems and fails randomly even on these. The process I usually take to determine the delta for these kind of tests is following:

* Do number of measurements across different systems
  most likely the slowest one would be small old ARM or a MIPS based router board

* Determine maximal measured delta from these, multiply it by two and use it as a delta for the test

**Comment by metan-ucw** [comment] 2018-06-22 12:41
Not so fast, the default value is too low, we should fix that in the upstream repo.

**Comment by metan-ucw** [comment] 2021-02-17 13:37
This has been fixed in 65b70fc4981f745a9394430abc4a0e2a8fa6ce64.

**Closed by metan-ucw** 2021-02-17 13:37 UTC
