### ISSUE TITLE
Few of the LTP tstcases are failing in SLES distro(kernel version-5.3.18)

### ISSUE THREAD

**Issue by shirishaganta1** [linux-test-project/ltp#783] opened 2021-02-04 10:01 UTC
LTP tests failed: ['semctl09', 'fs_fill', 'ksm03', 'ksm03_1', 'ksm04', 'ksm04_1',  'netns_comm_ns_exec_ipv4_netlink', 'netns_comm_ns_exec_ipv6_netlink', 'netns_comm_ip_ipv4_netlink', 'netns_comm_ip_ipv6_netlink', 'memcg_stat', 'memcg_use_hierarchy', 'cpuset_inherit', 'cpuset_hotplug',  'crypto_user02', 'zram01', 'zram02', 'zram03']

Below attaching the failed log. And please let us know do you need any data from our side
[file_190971.txt](https://github.com/linux-test-project/ltp/files/5924767/file_190971.txt)

**Comment by metan-ucw** [comment] 2021-02-08 09:58
The semctl failures are actually caused by a glibc bug, see https://bugzilla.suse.com/show_bug.cgi?id=1181305

As for the fs_fill it seems to be timeouting on btrfs, no idea what is wrong there, you have to have a closer look yourself.

The ksm failures are reported here: https://github.com/linux-test-project/ltp/issues/734. Generally cgroup tests are being rewritten at the moment, do not expect that these would work well until the rewrite is finished.

Also you are not executing the tests properly, at least the zram test are not working as expected because of that, you have to set PATH environment variable or use runltp that does that for you, see https://github.com/linux-test-project/ltp#shortcut-to-running-a-single-test

**Comment by shirishaganta1** [comment] 2021-02-10 05:48
> As for the fs_fill it seems to be timeouting on btrfs, no idea what is wrong there, you have to have a closer look yourself.
will look into it
 
> Also you are not executing the tests properly, at least the zram test are not working as expected because of that, you have to set PATH environment variable or use runltp that does that for you, see https://github.com/linux-test-project/ltp#shortcut-to-running-a-single-test
Regarding zram I tried using ./runltp -f kernel_misc but still am seeing the same issue

Thanks for the details.

**Comment by pevik** [comment] 2021-02-10 08:34
`./zram_lib.sh: line 50: tst_kvcmp: command not found` shows missing dependency, thus I doubt you did `cd /opt/ltp` before.

Best is to follow installation instruction, i.e. also run `make install` and then run `/opt/ltp/runltp -f kernel_misc`. If you run just from git tree, you need to run make in `testcases/lib` and have it also in `PATH` (as noted in link metan-ucw posted). But that might not be enough (network tests needs even more), thus please compile everything (https://github.com/linux-test-project/ltp#quick-guide-to-running-the-tests).

**Comment by metan-ucw** [comment] 2021-05-14 13:19
Let's close this now. Fee free to reopen if you still see unexpected failures.

**Closed by metan-ucw** 2021-05-14 13:19 UTC
