### ISSUE TITLE
mtest05 fail on read only remote machine

### ISSUE THREAD

**Issue by NgaHoang10** [linux-test-project/ltp#87] opened 2016-08-29 09:33 UTC
2016-08-26T11:37:31 Test: mtest05 Testparm: mmstress
mmstress    0  TINFO  :  run mmstress -h for all options
mmstress    0  TINFO  :  test1: Test case tests the race condition between simultaneous read faults in the same address space.
mmstress    1  TFAIL  :  mmstress.c:927: TEST 1 Failed
mmstress    0  TINFO  :  test2: Test case tests the race condition between simultaneous write faults in the same address space.
map_and_thread(): open(): Read-only file system
map_and_thread(): open(): Read-only file system
......
I run tests on read-only remote machine

Looks like the test tries to create new file in test binary folder..
map_and_thread("./tmp.file.1", thread_fault, READ_FAULT, NUMTHREAD, &retval);

**Comment by metan-ucw** [comment] 2016-08-29 10:25
Indeed the test opens files in ```$CWD``` it should be fixed to honour ```$TMPDIR``` and create a temporary directory there before it starts testing.

**Comment by bssrikanth** [comment] 2016-11-23 06:41
trying to recreate this issue locally.. I am having CWD which is read-only.. but able to run tests successfully
/tmp/imgmnt# touch d
touch: cannot touch 'd': Read-only file system  <-- CWD is readonly

/tmp/imgmnt# /opt/ltp/runltp -s mtest05
 mmstress    0  TINFO  :  run mmstress -h for all options
mmstress    0  TINFO  :  test1: Test case tests the race condition between simultaneous read faults in the same address space.
mmstress    1  TPASS  :  TEST 1 Passed
mmstress    0  TINFO  :  test2: Test case tests the race condition between simultaneous write faults in the same address space.
mmstress    2  TPASS  :  TEST 2 Passed
mmstress    0  TINFO  :  test3: Test case tests the race condition between simultaneous COW faults in the same address space.
mmstress    3  TPASS  :  TEST 3 Passed
mmstress    0  TINFO  :  test4: Test case tests the race condition between simultaneous READ faults in the same address space. The file mapped is /dev/zero
mmstress    4  TPASS  :  TEST 4 Passed
mmstress    0  TINFO  :  test5: Test case tests the race condition between simultaneous fork - exit faults in the same address space.
mmstress    5  TPASS  :  TEST 5 Passed
mmstress    0  TINFO  :  test6: Test case tests the race condition between simultaneous fork -exec - exit faults in the same address space.
mmstress    6  TPASS  :  TEST 6 Passed
mmstress    7  TPASS  :  Test Passed
<<<execution_status>>>
initiation_status="ok"
duration=1 termination_type=exited termination_id=0 corefile=no
cutime=89 cstime=882
<<<test_end>>>
INFO: ltp-pan reported all tests PASS
LTP Version: 20160920-140-g65767d1

       ###############################################################

            Done executing testcases.
            LTP Version:  20160920-140-g65767d1
       ###############################################################

**Comment by metan-ucw** [comment] 2016-11-23 08:42
That is because the `runltp` script changes working directory to the `/opt/ltp/`. But you should be able to run the test binary directly in the read only directory, i.e. `/tmp/imgmnt# /opt/ltp/testcases/bin/mtest05` which should then fail.

**Comment by athira-rajeev** [comment] 2016-11-23 11:02
I was able to reproduce this issue . Created a file system and mounted as read only. 
Executed mmstress testcase.

mmstress    0  TINFO  :  run /root/athira/LTP/ltp/testcases/kernel/mem/mtest05/mmstress -h for all options
mmstress    0  TINFO  :  test1: Test case tests the race condition between simultaneous read faults in the same address space.
map_and_thread(): open(): Read-only file system
mmstress    1  TFAIL  :  mmstress.c:927: TEST 1 Failed
mmstress    0  TINFO  :  test2: Test case tests the race condition between simultaneous write faults in the same address space.
map_and_thread(): open(): Read-only file system
mmstress    2  TFAIL  :  mmstress.c:927: TEST 2 Failed
mmstress    0  TINFO  :  test3: Test case tests the race condition between simultaneous COW faults in the same address space.
map_and_thread(): open(): Read-only file system


Created patch for this testcase where:
- Create a directory under tmp using tst_tmpdir()
- Instead of creating file with "./tmp.file.1", create under tmpdir

Will post the patch

**Comment by Vertigo0709** [comment] 2016-12-07 04:18
Not sure when $CWD is updated (trying to export it to /tmp and run binary in another read-only directory is not help), but the testcase can run normally in /tmp
/tmp# /opt/ltp/testcases/bin/mmstress
mmstress    0  TINFO  :  run /opt/ltp/testcases/bin/mmstress -h for all options
mmstress    0  TINFO  :  test1: Test case tests the race condition between simultaneous read faults in the same address space.
mmstress    1  TPASS  :  TEST 1 Passed
mmstress    0  TINFO  :  test2: Test case tests the race condition between simultaneous write faults in the same address space.
mmstress    2  TPASS  :  TEST 2 Passed
mmstress    0  TINFO  :  test3: Test case tests the race condition between simultaneous COW faults in the same address space.
mmstress    3  TPASS  :  TEST 3 Passed
mmstress    0  TINFO  :  test4: Test case tests the race condition between simultaneous READ faults in the same address space. The file mapped is /dev/zero
mmstress    4  TPASS  :  TEST 4 Passed
mmstress    0  TINFO  :  test5: Test case tests the race condition between simultaneous fork - exit faults in the same address space.
mmstress    5  TPASS  :  TEST 5 Passed
mmstress    0  TINFO  :  test6: Test case tests the race condition between simultaneous fork -exec - exit faults in the same address space.
test6(): execvp(): No such file or directory
test6(): execvp(): No such file or directory

(test6 is failed just because "mmstress_dummy" is not in /tmp/)
So using tst_tmpdir() as @athira-rajeev recommended may help to fix all current issues
Waiting for your new patch :-)

**Comment by Vertigo0709** [comment] 2017-02-07 03:55
Hello @athira-rajeev 

> **Created** patch for this testcase where:
> 
>     Create a directory under tmp using tst_tmpdir()
>     Instead of creating file with "./tmp.file.1", create under tmpdir
> 
> Will post the patch

I also failed on this testcase, see that you already created the patch, did you post it ? (so that we'll not duplicate the work.)

**Closed** 2017-03-22 16:47 UTC
